# Jekyll config

# Site settings
title: Co-op design system
description: Co-op design system
baseurl: ""
url: "http://coop-design-manual.herokuapp.com"

# Build settings
source: ./src
destination: ./build
keep_files: ['css', 'js', 'assets']
markdown: kramdown

# Collections
collections:
  pattern-library:
    output: false

# Contentful
contentful:
  spaces:
    - design-system-content:
        space:        95z9ms2kvox3
        access_token: 9ee9badaa2d7bdf90b84b001b21358f267a8b6a17f72b5d14538ef0937d509ad
        environment:  master
        all_entries: true
        base_path: ./src

# Algolia
algolia:
  application_id: IYUPP0IQ1H
  index_name:     designsystem
